# Generated by Django 2.1.4 on 2019-01-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email_text',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='name_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
